apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentFrontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deploymentFrontend.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentFrontend.name }}
    spec:
      containers:
        - name: {{ .Values.deploymentFrontend.name }}
          image: {{ .Values.deploymentFrontend.image }}:{{ .Values.deploymentFrontend.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentFrontend.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.deploymentFrontend.name }}
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
