apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-backend
  template:
    metadata:
      labels:
        app: insurance-backend
    spec:
      containers:
        - name: insurance-backend
          image: insuranceregistry.azurecr.io/insurancetestproduction
          ports:
            - containerPort: 9096

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance-backend
  ports:
    - protocol: TCP
      port: 9096
      targetPort: 9096