apiVersion : apps/v1
kind: Deployment
metadata:
  name: "insurancekuber-fac2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "insurancekuber-fac2"
  template:
    metadata:
      labels:
        app: "insurancekuber-fac2"
    spec:
      containers:
        - name: "insurancekuber-fac2"
          image: "insuranceregistry.azurecr.io/insurancekuber"
          ports:
          - containerPort: 80