/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_dynamodb_all_tables_region": "ap-south-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "productsTable-dev",
            "region": "ap-south-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-south-1:73866d5f-b5cb-4f18-ad74-95e1db095d0f",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_qXhU8CQGO",
    "aws_user_pools_web_client_id": "75ls3h2h5svfonf7mivmtorlr1",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "productsapi",
            "endpoint": "https://quj063pm1j.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
